Lock down for now

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -462,7 +462,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar TOP_DIR BUILD_DIR CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL PDFLATEX HTLATEX LATEX MAKEINDEX BIBTEX DVIPS PS2PDF SWIG SWIGVERSION SWIGVERSIONMAJOR SWIGVERSIONMINOR SWIGVERSIONFLAGS TCL_LIB_DIR TCL_BIN_DIR TCLSH WISH TCL_INC_DIR TCL_LIBRARY HOSTTCLSH BWLIB SNITLIB UNZIP IMG_ZIP TCLKITRUN TCLXML_ZIP TCLKITBSRC BEXEEXT SED SHLIB_CFLAGS SHLIB_CXXFLAGS SHLIB_LD SHLIB_LD_LIBS SHLIB_SUFFIX TCL_DBGX TCL_VERSION TCL_DEFS TCL_LIBS TCL_STUB_LIB_SPEC TCL_STUB_LIB_PATH TCL_SHARED_LIBS TCL_SHARED_LIB_FILE TCL_UNSHARED_LIB_FILE TCL_SHLIB_CFLAGS TCL_SHLIB_SUFFIX TCL_SHLIB_LD TCL_PREFIX TCL_EXEC_PREFIX TCL_CFLAGS TCL_LIB_SPEC SYSTEMVERSION LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar TOP_DIR BUILD_DIR CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL PDFLATEX HTLATEX LATEX MAKEINDEX BIBTEX DVIPS PS2PDF SWIG SWIGVERSION SWIGVERSIONMAJOR SWIGVERSIONMINOR SWIGVERSIONFLAGS TCL_LIB_DIR TCL_BIN_DIR TCLSH WISH TCL_INC_DIR TCL_LIBRARY HOSTTCLSH BWLIB SNITLIB URILIB UNZIP IMG_ZIP TCLKITRUN TCLXML_ZIP TCLKITBSRC BEXEEXT SED SHLIB_CFLAGS SHLIB_CXXFLAGS SHLIB_LD SHLIB_LD_LIBS SHLIB_SUFFIX TCL_DBGX TCL_VERSION TCL_DEFS TCL_LIBS TCL_STUB_LIB_SPEC TCL_STUB_LIB_PATH TCL_SHARED_LIBS TCL_SHARED_LIB_FILE TCL_UNSHARED_LIB_FILE TCL_SHLIB_CFLAGS TCL_SHLIB_SUFFIX TCL_SHLIB_LD TCL_PREFIX TCL_EXEC_PREFIX TCL_CFLAGS TCL_LIB_SPEC SYSTEMVERSION LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1045,6 +1045,7 @@ Optional Packages:
   --with-tcl=DIR          use Tcl binaries from DIR
   --with-bwlib=DIR          use BWidget from DIR
   --with-snitlib=DIR          use snit from DIR
+  --with-urilib=DIR          use uri from DIR
 
 Some influential environment variables:
   CC          C compiler command
@@ -5272,7 +5273,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5275 "configure"' > conftest.$ac_ext
+  echo '#line 5276 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6146,7 +6147,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6149:" \
+echo "$as_me:6150:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7180,11 +7181,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7183: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7184: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7187: \$? = $ac_status" >&5
+   echo "$as_me:7188: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -7413,11 +7414,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7416: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7417: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7420: \$? = $ac_status" >&5
+   echo "$as_me:7421: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -7473,11 +7474,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7476: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7477: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7480: \$? = $ac_status" >&5
+   echo "$as_me:7481: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8807,7 +8808,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 8810 "configure"' > conftest.$ac_ext
+    echo '#line 8811 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9678,7 +9679,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9681 "configure"
+#line 9682 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9776,7 +9777,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9779 "configure"
+#line 9780 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11955,11 +11956,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11958: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11959: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11962: \$? = $ac_status" >&5
+   echo "$as_me:11963: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12015,11 +12016,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12018: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12019: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12022: \$? = $ac_status" >&5
+   echo "$as_me:12023: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12526,7 +12527,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 12529 "configure"' > conftest.$ac_ext
+    echo '#line 12530 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -13397,7 +13398,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13400 "configure"
+#line 13401 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13495,7 +13496,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13498 "configure"
+#line 13499 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14322,11 +14323,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14325: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14326: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14329: \$? = $ac_status" >&5
+   echo "$as_me:14330: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14382,11 +14383,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14385: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14386: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14389: \$? = $ac_status" >&5
+   echo "$as_me:14390: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15696,7 +15697,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 15699 "configure"' > conftest.$ac_ext
+    echo '#line 15700 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -16437,11 +16438,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16440: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16441: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16444: \$? = $ac_status" >&5
+   echo "$as_me:16445: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16670,11 +16671,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16673: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16674: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16677: \$? = $ac_status" >&5
+   echo "$as_me:16678: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16730,11 +16731,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16733: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16734: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16737: \$? = $ac_status" >&5
+   echo "$as_me:16738: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18064,7 +18065,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 18067 "configure"' > conftest.$ac_ext
+    echo '#line 18068 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18935,7 +18936,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18938 "configure"
+#line 18939 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19033,7 +19034,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19036 "configure"
+#line 19037 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20989,6 +20990,32 @@ echo "$as_me: error: Snit library directory $SNITLIB doesn't exist" >&2;}
 fi
 
 
+echo "$as_me:$LINENO: checking uri dir" >&5
+echo $ECHO_N "checking uri dir... $ECHO_C" >&6
+URILIB=`echo 'puts $tcl_library'|${HOSTTCLSH}`
+
+dirs="${TCL_PREFIX}/lib/uri* ${TCL_PREFIX}/lib/tcllib*/uri* ${URILIB}/../tcllib*/uri* ${URILIB}/../uri* ${URILIB}/tcllib*/uri* ${URILIB}/uri*"
+for i in $dirs ; do
+  if test -d "$i" -a -f "$i/pkgIndex.tcl"; then
+    URILIB=`cd $i; pwd`
+  fi
+done
+
+# Check whether --with-urilib or --without-urilib was given.
+if test "${with_urilib+set}" = set; then
+  withval="$with_urilib"
+  URILIB=$withval
+fi;
+if test -d $URILIB; then
+   echo "$as_me:$LINENO: result: using uri library in $URILIB" >&5
+echo "${ECHO_T}using uri library in $URILIB" >&6
+else
+   { { echo "$as_me:$LINENO: error: Uri library directory $URILIB doesn't exist" >&5
+echo "$as_me: error: Uri library directory $URILIB doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
 for ac_prog in unzip
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -21985,6 +22012,7 @@ s,@TCL_LIBRARY@,$TCL_LIBRARY,;t t
 s,@HOSTTCLSH@,$HOSTTCLSH,;t t
 s,@BWLIB@,$BWLIB,;t t
 s,@SNITLIB@,$SNITLIB,;t t
+s,@URILIB@,$URILIB,;t t
 s,@UNZIP@,$UNZIP,;t t
 s,@IMG_ZIP@,$IMG_ZIP,;t t
 s,@TCLKITRUN@,$TCLKITRUN,;t t
